apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventoryservice
  labels:
    app: inventoryservice
spec:
  selector:
    matchLabels:
      app: inventoryservice
  template:
    metadata:
      labels:
        app: inventoryservice
    spec:
      serviceAccountName: inventoryservice
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: inventoryservice
          ports:
          - containerPort: 50052
          readinessProbe:
            grpc:
              port: 50052
          livenessProbe:
            grpc:
              port: 50052
          env:
          - name: PORT
            value: "50052"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: inventoryservice
  labels:
    app: inventoryservice
spec:
  type: ClusterIP
  selector:
    app: inventoryservice
  ports:
  - name: grpc
    port: 50052
    targetPort: 50052
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventoryservice
